In [69]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

In [51]:
df = pd.read_csv('iris.csv')

In [52]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [53]:
df.shape

(150, 5)

In [54]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [55]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [56]:
df.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [46]:
le = LabelEncoder()

In [58]:
df.species = le.fit_transform(df.species)

In [61]:
X = df.drop('species',axis=1)

In [62]:
y = df['species']

In [65]:
X_train , X_test, y_train, y_test =  train_test_split(X,y,test_size=0.2)

In [67]:
classifier = SVC(kernel='poly',degree=8)
classifier.fit(X_train,y_train)

SVC(degree=8, kernel='poly')

In [71]:
y_pred = classifier.predict(X_test)

In [73]:
print(confusion_matrix(y_test,y_pred))

[[13  0  0]
 [ 0 12  0]
 [ 0  1  4]]


In [74]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.92      1.00      0.96        12
           2       1.00      0.80      0.89         5

    accuracy                           0.97        30
   macro avg       0.97      0.93      0.95        30
weighted avg       0.97      0.97      0.97        30



In [75]:
classifier1 = SVC(kernel='rbf')
classifier1.fit(X_train,y_train)

SVC()

In [76]:
y_predd = classifier1.predict(X_test)

In [77]:
print(confusion_matrix(y_test,y_predd))

[[13  0  0]
 [ 0 11  1]
 [ 0  0  5]]


In [78]:
print(classification_report(y_test,y_predd))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.92      0.96        12
           2       0.83      1.00      0.91         5

    accuracy                           0.97        30
   macro avg       0.94      0.97      0.96        30
weighted avg       0.97      0.97      0.97        30



In [88]:
classifier2 = SVC(kernel='sigmoid')
classifier2.fit(X_train,y_train)

SVC(kernel='sigmoid')

In [89]:
y_preddd = classifier2.predict(X_test)

In [90]:
print(confusion_matrix(y_test,y_preddd))
print(classification_report(y_test,y_preddd))

[[ 0  0 13]
 [ 0  0 12]
 [ 0  0  5]]
              precision    recall  f1-score   support

           0       0.00      0.00      0.00        13
           1       0.00      0.00      0.00        12
           2       0.17      1.00      0.29         5

    accuracy                           0.17        30
   macro avg       0.06      0.33      0.10        30
weighted avg       0.03      0.17      0.05        30

