In [172]:
import pandas as pd 
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [149]:
df = pd.read_csv('iris.csv')

In [150]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [151]:
le = LabelEncoder()

In [142]:
df['species'] = le.fit_transform(df['species'])

In [143]:
df1 = df

In [144]:
scaler = StandardScaler()

In [145]:
y = scaler.fit_transform(df1.drop('species',axis=1))

In [146]:
df2 = pd.DataFrame(y,columns=df.columns[:-1])

In [147]:
df2

sepal_length  sepal_width  petal_length  petal_width
0       -0.900681     1.032057     -1.341272    -1.312977
1       -1.143017    -0.124958     -1.341272    -1.312977
2       -1.385353     0.337848     -1.398138    -1.312977
3       -1.506521     0.106445     -1.284407    -1.312977
4       -1.021849     1.263460     -1.341272    -1.312977
..            ...          ...           ...          ...
145      1.038005    -0.124958      0.819624     1.447956
146      0.553333    -1.281972      0.705893     0.922064
147      0.795669    -0.124958      0.819624     1.053537
148      0.432165     0.800654      0.933356     1.447956
149      0.068662    -0.124958      0.762759     0.790591

[150 rows x 4 columns]

In [154]:
X = df2
y= df1['species']

In [156]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [166]:
knn_classifier = KNeighborsClassifier(n_neighbors=3)

In [168]:
knn_classifier.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [170]:
y_pred = knn_classifier.predict(X_test)

In [171]:
y_pred

array([1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1, 1, 0, 0, 2, 0, 2, 1, 2,
       1, 2, 0, 0, 1, 1, 0, 0, 0, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 0, 2,
       0])

In [173]:
print(confusion_matrix(y_test,y_pred))

[[10  1  0]
 [ 0 15  1]
 [ 0  4 14]]


In [174]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      0.91      0.95        11
           1       0.75      0.94      0.83        16
           2       0.93      0.78      0.85        18

    accuracy                           0.87        45
   macro avg       0.89      0.87      0.88        45
weighted avg       0.88      0.87      0.87        45

