In [36]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import  classification_report, confusion_matrix

In [22]:
df = pd.read_csv("iris.csv")

In [23]:
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [24]:
le = LabelEncoder()

In [25]:
df.species = le.fit_transform(df.species)

In [28]:
X = df.drop('species',axis=1)
y = df['species']

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [32]:
classifier = GaussianNB()

In [35]:
classifier.fit(X_train,y_train)

GaussianNB()

In [38]:
y_pred = classifier.predict(X_test)

In [41]:
print(confusion_matrix(y_test,y_pred))

[[ 9  0  0]
 [ 0 10  2]
 [ 0  0  9]]


In [42]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       1.00      0.83      0.91        12
           2       0.82      1.00      0.90         9

    accuracy                           0.93        30
   macro avg       0.94      0.94      0.94        30
weighted avg       0.95      0.93      0.93        30

